### ISSUE TITLE
data info throws invalid error message when remote URL is invalid

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#213] opened 2017-11-24 09:34 UTC
When I try to run `data info` for remote invalid url, it gives the following invalid error message
`> Error! File is not in known tabular format.`

**Comment by anuveyatsu** [comment] 2018-02-28 19:35
DUPLICATE of https://github.com/datahq/data-cli/issues/303

**Closed as completed by anuveyatsu** 2018-02-28 19:35 UTC
Labels: duplicate
