### ISSUE TITLE
[login] QA review 8 Aug 2017

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#140] opened 2017-08-08 17:26 UTC
* After `login` command, `username` generated with my entire gmail. Checked in DB, it is `username`: `meiran1991@gmail.com`. 
* If I login with `data login` -> remove `~/.datahub.json` -> and run `data login --api https://api-testing.datahub.io`
	* Says I'm already logged in, while I'm not (for testing)
* Run data login with invalid API url results with unclear error message. Eg `data login --api https://testing-api.datahub.com` 
```
Error! Connection error: request to https://api-testing.datahub.com/auth/check?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyaWQiOiIwZTliNTljZDUwZjE4ODQwNThjMWFhMjQyZDcxYTIyOCIsImV4cCI6MTUwMzQwMzE0N30.SEhOF5yZqXyqOVDJ1D6MiFgnyFDXKmITD9tN64LhLhk&next=http://localhost:3000 failed, reason: getaddrinfo ENOTFOUND api-testing.datahub.com api-testing.datahub.com:443
```

**Comment by rufuspollock** [comment] 2017-08-09 16:46
> After login command, username generated with my entire gmail. Checked in DB, it is username: meiran1991@gmail.com.

@zelima  Isn't this an issue with https://github.com/datahq/auth/issues/16 - google usernames should not include the gmail.com part right ...

> If I login with data login -> remove ~/.datahub.json -> and run data login --api https://api-testing.datahub.io
> Says I'm already logged in, while I'm not (for testing)

For me this is not a bug. At the moment we don't support different site configs at the same time (testing is only used by us devs ...)

> Run data login with invalid API url results with unclear error message. Eg data login --api https://testing-api.datahub.com

Again, this is rare. However, it could be part of a larger issue about how we handle inet problems (e.g. connection breaking etc). That would be a separate specific issue though.

**Overall: I think this is probably an INVALID / WONTFIX atm**

**Comment by anuveyatsu** [comment] 2017-08-30 06:29
INVALID
username part is fixed in https://github.com/datahq/auth/issues/16 and other points are invalid.

**Closed as completed by anuveyatsu** 2017-08-30 06:29 UTC
Labels: invalid
